alias grep='grep --color=auto'
alias xclip='xclip -selection clipboard'
alias ls='eza -T --icons --group-directories-first -I ".git" --git-ignore -L2'
alias clear='printf "\033[3J\033[H\033[2J"'
alias rmd='rm -rf'
alias icat='kitten icat --align left'

alias firefox='firefox & disown'
alias discord='vesktop & disown'
alias yt='ytfzf'
alias ddg='ddgr'
alias music='kew'
alias woman='man'

alias ..='cd ..'
alias ...='cd ../..'
