alias grep='grep --color=auto'
alias clip='kitten clipboard'
alias ls='eza -T --icons --group-directories-first -I ".git" --git-ignore -L2'
alias clear='printf "\033[3J\033[H\033[2J"'
alias rmd='rm -rf'
alias icat='kitten icat --align left'
alias neofetch='fastfetch'
alias pixelorama='/usr/bin/Pixelorama-Linux-64bit/Pixelorama.x86_64'

alias firefox='firefox & disown'
alias discord='vesktop & disown'
alias vbox='virtualbox & disown'

alias yt='ytfzf'
alias ddg='ddgr'
alias music='kew'
alias woman='man'

alias ..='cd ..'
alias ...='cd ../..'
