# Stuff #
enable_audio_bell		no
window_padding_width	5 10 5 10
cursor_shape			block
allow_remote_control	yes
listen_on               unix:/tmp/kitty

# Tabs #
tab_bar_style           powerline
tab_powerline_style     angled
active_tab_foreground   #281d28
active_tab_background   #ebdbb2
inactive_tab_foreground #ebdbb2
inactive_tab_background #281d28
map ctrl+enter          new_tab
map ctrl+q              close_tab
map ctrl+h              move_tab_backward
map ctrl+l              move_tab_forward
map ctrl+t              set_tab_title

# Fonts #
font_family			    Source Code Medium
symbol_map			    U+F1900-U+F19FF nasin-nanpa
bold_font        	    auto
italic_font         	auto
bold_italic_font 	    auto

# Color #
background            #281d28
foreground  		  #ebdbb2
cursor                #928374
selection_foreground  #928374
selection_background  #3c3836

color0                #282828
color8                #928374
color1                #cc241d
color9                #fb4934
color2                #98971a
color10               #b8bb26
color3                #d79921
color11               #fabd2d
color4                #458588
color12               #83a598
color5                #b16286
color13               #d3869b
color6                #689d6a
color14               #8ec07c
color7                #a89984
color15               #928374
