backend = "glx";
vsync = false;

blur: {
	method = "dual_kawase";
	strength = 0;
	background = true;
};
blur-size = 0;
blur-background-exclude = [
	"class_g = 'Polybar'",
];

opacity-rule = [
	"100:class_g = 'Polybar'",
	"95:focused",
	"60:!focused",
	"75:class_g = 'Kitty'",
];

shadow = true;
shadow-exclude = [
	"class_g = 'Polybar'",
];
