backend = "glx";
vsync = false;

opacity-rule = [
    "100:class_g = 'Rofi'",
	"100:class_g = 'Polybar'",
	"95:focused",
	"60:!focused",
	"75:class_g = 'Kitty'",
];

shadow = true;
shadow-exclude = [
	"class_g = 'Polybar'",
];
