backend = "glx";
vsync = false;

opacity-rule = [
	"75:class_g = 'Kitty'",
	"75:class_g = 'i3bar'",
	"75:class_g = 'polybar'"
];

blur:
{
	method = "dual_kawase";
	strength = 0;
	background = true;
};
blur-size = 3;

shadow = false;
shadow-radius = 12;
shadow-opacity = 0.7;
